# Generated by Django 4.2.6 on 2023-10-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_request_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='request',
            name='subject',
            field=models.CharField(default='Asunto no especificado', max_length=200),
        ),
    ]
