# Generated by Django 4.2.6 on 2023-10-18 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_userworkday'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkday',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='userworkday',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
