# Generated by Django 4.2.6 on 2023-10-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_userworkday_created_at_userworkday_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='date_posted',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
